[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
iota-client = { path = "../iota.rs/client"}

lets = { path = "../streams/lets"}
streams = { path = "../streams/streams"}

identity_did = { path = "../identity.rs/identity_did"}
identity_iota = { path = "../identity.rs/identity_iota"}

iota_stronghold = { path = "../stronghold.rs/client"}